---
title: "No exit: the conservation reliance of species with too little habitat"
output:
    bookdown::word_document2:
        reference_docx: ms_general.docx
        number_sections: false
    bookdown::pdf_document2:
        toc: no
        latex_engine: xelatex
        fig_caption: yes
        keep_tex: yes
link-citations: yes
csl: conservation-letters.csl
biblio-style: apalike
bibliography: [refs.bib, funky-refs.bib, pckgs.bib]
fontsize: 12pt
geometry: margin=2.5cm
mainfont: Calibri
lang: en-GB
papersize: a4
documentclass: article
header-includes:
- \usepackage{hyperref}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[CO,CE]{\thepage}
- \usepackage{setspace}
- \doublespacing
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
knitr::opts_chunk$set(echo = FALSE,message = FALSE,error = FALSE, warning = FALSE,
                      dpi = 300, fig.path = "output/main/", fig.align = "center", 
                      fig.width = 16.6/2.54, fig.height = 15/2.54)
```

_______________________________________________________________________________________

Sophia Richter^1^ , Rebecca A. Senior^2^*, and David S. Wilcove^1,2^

^1^Department of Ecology and Evolutionary Biology, Princeton University, Princeton, NJ, USA.

^2^Princeton School of Public and International Affairs, Princeton University, Princeton, NJ, USA.

*__Corresponding author:__ rebecca.a.senior@gmail.com (R.A. Senior)

__ORCID iDs:__ orcid.org/0000-0002-8208-736X (R.A. Senior)
  
__Authorship:__ R.A.S. and D.S.W. conceived the study. R.A.S. collated the data. S.R. carried out the analyses and wrote the first draft of the manuscript, with substantial contribution from R.A.S. and D.S.W. 

__Funding:__ High Meadows Environmental Institute and High Meadows Foundation.

__Key words:__ conservation; extinction; IUCN Red List; conservation planning; biodiversity; threatened species

__Article type:__ Perspective

__Number of words:__ 

__Number of References:__ 

__Number of Figures:__ ; __Number of Tables:__ 0 

Conservation Letters formatting guidelines:

Perspectives provide a forum for authors to discuss recent developments or ideas with broad and significant policy relevance to conservation. They should be forward looking and written with a view to informing non-specialist readers (thus should be presented using straightforward prose and avoiding jargon). Perspectives may be up to 3000 words in length and should contain no more than 5 figures and/or tables, and fewer than 30 references.

# Abstract


__/200 words__

# Introduction

<!-- This is a good start, but we will need to restructure to improve clarity and make the whole thing more captivating. If we are telling a global story, we don't want to focus excessively on very fine-scale details - keep it on the big picture. The Intro doesn't have to be only five paras, but something similar to the following structure is, I think, more what we're aiming for: -->

<!-- P1 = biodiversity loss is a problem, driven primarily by habitat loss therefore will continue to be a problem -> need to care about how much habitat species have -->

<!-- P2 = link between habitat area and extinction risk; this should briefly touch on environmental stochasticity (environmental perturbations more likely to effect entire population), demographic stochasticity (sex ratio imbalance, inbreeding, loss of genetic diversity -> impaired potential for local adaptation), and edge effects (smaller habitat means more edge relative to interior, which causes additional problems)  -->

<!-- P3 = given the link between habitat area and extinction risk, IUCN Red List use habitat area as one of the five listing criteria; since a species need only meet one criteria to be listed in that category, we know intuitively that habitat area has the potential to be a limiting factor for downlisting species on the Red List, reflecting the reality that populations cannot recover and expand if there is insufficient habitat -->

<!-- P4 = in terms of habitat area, there are two, related and important facets: (1) how close are species to getting worse?; and (2) how far are species from getting better? It is timely to address both, given the updating of relevant policy frameworks. In the first instance, species need habitat protection to maintain status quo -> 30 x 30. In the second instance, need to identify the species that are conservation reliant to be able to pragmatically allocate resources and optimally prioritise areas for habitat restoration -> SDGs and Bonn Challenge -->

<!-- P5 = what we did -> to answer questions (1) and (2), and so guide post-2020 conservation policy, we capitalised on recent advances in availability of habitat maps to calculate AOH for all species within taxonomic groups that have been comprehensively assessed by the Red List, and compared AOH to the Red List thresholds under criterion B to identify the so-called 'No Exit Species'-->

The world is currently experiencing a biodiversity crisis [@wwf_living_2020; @rosenberg_decline_2019]. Habitat conversion is the leading cause of species extinctions, across all anthropic changes on Earth [@maxwell_biodiversity:_2016;@goncalves-souzaHabitatLossExtinction2020]. Among the biggest drivers of species extinctions is habitat loss, with the destruction of habitat driven largely by agricultural expansion [@wwf_living_2020; @williams_proactive_2020; @gibbs_tropical_2010]. As demand for food increases, driven by population growth and eating habits, so the climate and agricultural sector is expected to grow and develop in tandem. Improvements in efficiency, such as increasing yields per area, decreasing waste, and shifting away from meat-based diets in some cultures [@tilman_global_2011; @tilman_future_2017; @williams_proactive_2020], could help to abate habitat loss for some threatened species, but many will face further conversion of primary habitat - particularly in the tropics [@gibbs_tropical_2010]. Because habitat destruction is one of the most influential factors in species extinction, and will continue to be so into the future, preventing and managing habitat destruction is a central issue in conservation and ecology [@liaoModellingPlantPopulation2013].  

Habitat loss leads to habitat fragmentation and smaller habitat areas. This has a significant effect on a species’ risk of extinction, in particular when combined with stochastic effects. The amount of environmental variation a population undergoes is highly dependent on area of habitat. Because most environmental stressors are localized, a population with a large area of habitat benefits from the averaging effect of environmental effects that are not over the entire range, while populations with a small habitat are at a much higher risk of extinction because environmental changes are likely to affect the entire population [@lacyConsideringThreatsViability2000]. Habitat fragmentation increases the risk of extinction in part due to its association with loss of habitat area [@crooksQuantificationHabitatFragmentation2017; @reedExtinctionRiskFragmented2004a]. In addition, fragmented habitats have a greater relative amount of edge, bringing concomitant edge effects like higher temperatures and easier access for poachers [@ewers_fragmentation_2013;pfeifer_creation_2017], and the isolation of fragmented habitat can make it difficult for species to disperse elsewhere [@crooks_global_2011;haddad_habitat_2015]. 

<!-- As a big picture paper, we need to focus either on big picture examples, or multiple regional examples spread across the world. That is why I removed the example below.-->
<!-- while habitat loss within a species’ range was found to be the leading factor inhibiting recovery for species in Canada [@kerrHabitatLossLimits2004]. Habitat loss, therefore, will continue to be a major concern in conservation.   -->

<!-- I know that I wrote the bones of the para below, but as the paper has developed this para needs to adapt. You have read the conservation reliance literature more thoroughly than me, so you need to decide how the 'conservation reliance' angle fits in. Scott et al. 2010 state that CRS are species where the "maintenance of viable populations of many species will require continuing, species-specific intervention". Thus, we need to make the case that species with restricted habitat will be CRS because they are more vulnerable to stochastic effects, and can never move beyond this without gains in habitat area, no matter what other actions are implemented. I think we should still focus on these being 'No Exit Species' rather than CRS, but the link to conservation reliance is still useful. -->

The IUCN Red List documents species' current risk of extinction, based on thorough assessments of their status and the threats that they face [@mace_quantification_2008; @iucn_iucn_2020]. Of the five criteria under which a species can be listed as threatened, several are directly or indirectly related to the amount of existing habitat available to a given species. The conservation literature has discussed in detail the issue of 'conservation reliance' [@scott_conservation-reliant_2010; @goble_conservation-reliant_2012; @scott_recovery_2005], in the context of species that are unlikely to persist without sustained conservation interventions, such as prescribed burning. However, a related but under-explored area of conservation reliance lies in the extent to which species are committed to their current Red List category (or worse), simply because they do not have enough habitat remaining for downlisting to ever be possible.   

<!-- The para below is too techy/jargon-filled and doesn't grab the reader. Also a couple of things to note re markdown docs: -->

<!-- (1) If you want to come back and add a citation later, I recommend doing something like @REF or @CITE, because then when you knit the doc it will come up with a warning that it couldn't find the citation 'REF' or 'CITE' and that will remind you to go back and fill in the citation -->
<!-- (2) I'm not sure why (copy & paste?) but some special characters have been introduced that cause problems when knitting. I'm thinking in particular of the quotation mark symbols “”, which should instead be plain text "". That ensures they are rendered correctly in the various different outputs that you might choose (Word/pdf/html). A find/replace in RStudio can fix this for you. -->

Thanks to recent advances in the resolution and extent of fine-scale habitat maps, it is now possible to refine species’ distribution data for all species with both spatial range data and information on habitat preferences, allowing us to quantify Area of Occurrence (AOO) at broad-scale, in a standardised way [@brooks_measuring_2019;@santini_applying_2019]. Criterion B2 of the IUCN Red List directly relates to AOO to qualify for a Red List category, in which if a species' AOO is below a threshold value and meets 2 of 3 conditions it qualifies for that classification [@iucn_guidelines_2019]. While Extent of Occurrence (EOO) is the continuous boundary in which all known sites of occurrence are included, Area of Occupancy (AOO) is the area within the EOO in which the species actually occupies. EOO may include unoccupied or unsuitable habitats, such as incompatible elevation or water sources, and is therefore a less accurate measure of a species' habitat than AOO. With AOH for all threatened, terrestrial vertebrates, we can easily identify species with insufficient habitat. Comparing current AOO to the IUCN Red List thresholds reveals the species that, at present, could never qualify for future downlisting and can be classified as "No Exit Species" (NES).  

<!-- * Try not to overuse 'these' as a reference to a previous thing, and particularly not if that thing was in a different para. Every para should be able to be read somewhat independently. -->
<!-- * Recommend avoiding the word significant for anything other than statistical significance -->
<!-- * 30 x 30 is a global thing, that different countries will probably sign up to at the UN Biodiversity Conference. The US, UK and other countries have already made the commitment, but it is anticipated that it will be global. -->
<!-- * The policy pegs need to be up front and centre in this paper - reads like an afterthought at the moment -->

Without substantial gains in habitat area, NES are always at heightened risk of extinction. Regardless of the other interventions we take - including captive breeding, habitat protection, invasive species removal and more - extinction risk of NES can never be reduced without increasing the amount of available habitat. All else being equal, NES can only ever be uplisted to a higher risk IUCN category. Thus, policy changes are needed to aid these species and prevent loss of biodiversity. The 30 by 30 goal to protect 30 percent of the world's land and coastal seas by 2030 [@bidenExecutiveOrder140082021] and Goal 15 of the Sustainable Development Goals (SDGs) is to halt and reverse land degradation and halt biodiversity loss [@TransformingOurWorld2015], both of which will aid in the protection of habitat area for these species and prevent uplisting due to habitat loss. Simultaneously, the Bonn Challenge to restore 150 million hectares of degraded and deforested landscapes by 2020 and 350 million hectares by 2030 [@BonnChallenge2016] allows for NES the ability to expand their area of habitat and improve in Red List category.  

Ultimately, informed decisions need to be made by the relevant local stakeholders regarding whether it is possible and desirable to increase habitat area. The cost of conservation is considerable and particularly draining for organizations with limited resources and funding. The median Individual Conservation Cost (ICC) for a cheetah, for example, is 6,898 (USD) and 3,140 (USD) for a leopard [@weiseFinancialCostsLarge2014]. If gains in habitat quantity cannot be achieved for the NES, we must then consider whether other conservation interventions are worthwhile purely as a means to maintain the status quo, or whether such interventions are a drain on limited conservation resources for species with no hope of recovery.

# Methods

## Area of Habitat

To assess which species are reliant on habitat restoration (NES) we define habitat as Area of Habitat (AOH), which we calculated following @brooks_measuring_2019. In brief, AOH maps were produced for all threatened, terrestrial species in taxonomic groups that have range maps and have been comprehensively assessed by the IUCN Red List to at least family level (all amphibians, birds and mammals, but select families in the classes Magnoliopsida and Reptilia). Range maps were downloaded from the websites of the Red List [@iucn_iucn_2020] and BirdLife International [@birdlife_2020], and refined to AOH by retaining only grid cells that fall within the range polygons, and meet the species' habitat and elevation preferences as defined by the Red List [@iucn_iucn_2020]. All spatial analyses were conducted in Google Earth Engine[@gorelick_google_2017].

Following Red List assessment protocol [@iucn_guidelines_2019], we exclude habitats that are defined by the Red List as 'marginal' in their suitability, or 'passage' in their seasonality of use. As we are interested in the minimum habitat area needed to sustain a healthy global population, for migratory species we consider only the smaller of either the breeding or non-breeding range, in keeping with the Red List protocol [@iucn_guidelines_2019]. We do, however, retain habitat types listed with 'unknown' suitability or seasonality, because this likely affects many threatened species that are simply too rare or poorly known for such classification to be possible.

To identify cells with suitable habitat, we used the 1 km-resolution IUCN habitat types map for the year 2015 [@jung_global_2020]. Level 1 habitat categories refer to the broad categories of Forest, Savanna, Shrubland, Grassland, Wetlands (inland), Rocky Areas, Deserts and Artificial habitats, each of which contains finer level 2 categories, e.g., 'Forest - Boreal'. Where a species' habitat preference is given only to level 1, we conservatively assume that all nested level 2 categories are also suitable. To identify cells with suitable elevation, we use version 3 of the Digital Elevation Map from the Shuttle Radar Topography Mission (SRTM v3). All maps were resampled to 2 km, following @iucn_guidelines_2019, projected to a Mollweide projection to ensure accuracy of area calculations. 

To quantify the extent to which AOH is a limiting factor in decreasing a species' risk of extinction, we compare AOH to the fixed thresholds used by the Red List to assign species to the Red List categories. The Red List use five criteria for this classification, and species are assigned to the highest risk category for which they qualify under any of the criteria [@iucn_guidelines_2019]. Here, we are specifically referring to criterion B, under which species are classified based on their geographic range. The area of a species' range can be measured based on Extent of Occurrence (EOO) or Area of Occupancy (AOO). The former generally refers to the area of the smallest convex hull that can be drawn to encompass all occurrences of a species, while the AOO is the subset of the EOO where the species actually occurs [@iucn_guidelines_2019]. Thus, AOH is analagous to AOO and can be used in the same way, using the same thresholds [@brooks_measuring_2019]. 

For the three 'threatened' Red List categories of Vulnerable, Endangered and Critically Endangered, the AOH thresholds are, respectively: < 2000 km^; < 500 km^2; and, < 10 km^2. We categorise species as 'No Exit' if their AOH falls below any of the three thresholds. We futher require that species are at least 1 km^2 from that threshold, based on the assumption that 1 km^2 is a trivial difference that can be gained or lost easily, and is within the error of the spatial data. We note that when the Red List use these thresholds for classification, they additionally require that two out of three subcriteria are met. However, several additional metrics would be needed to assess these subcriteria (habitat fragmentation, and temporal trends in population size or habitat quantity or quality) [@santini_applying_2019]. Such classification is beyond the scope of this study, as we are interested not in automating Red List classification, but rather in the extent to which habitat quantity limits our ability to improve species' prospects. Here, when a species is classed as 'No Exit', we are referring to situations where no matter what other actions we might take to address threats and improve outcomes for threatened species, their small AOH means that No Exit Species will always be limited in the extent to which extinction risk can be mitigated.

In downstream analyses, we first summarize the taxonomy and biogeography of NES. Next, we explore the magnitude of species' reliance on habitat by calculating the difference between species' AOH and the threshold for downlisting. This difference is the amount of habitat that a species would need to gain to have any chance of downlisting to a lower category of extinction risk on the Red List, regardless of what other conservation actions we might take. We summarize both the distribution of these differences to threshold, as well as the upper quantile of species within each habitat category that are furthest from the next threshold - the 'Extreme No Exit' species (ENES). ENES are the species with the most additional habitat required to safeguard them from extinction, and thus the species most likely to require major and concerted effort to save. The biogeographic distribution of NES and ENES was determined by resampling species' AOH to a 0.25 degree resolution grid (approximately 30 km at the equator), and summing the number of NES and ENES occurring in each country [@gadm_2018] and zoogeographic realm [@holt_update_2013].  

<!-- The below we can come back to in the Discussion -->
<!-- We also explore the difference between each species' listed category on the Red List and their habitat category. The difference is red list category subtracted from category as numerical values. -->

## Statistical analyses

<!-- RStudio is just a graphical interface, nobody cares what version it is. It's the R version that matters, because this can influence what a given piece of code does (that could feasibly change from one version to another). Get the R version using the function `R.version` -->
<!-- Using passive voice (i.e. 'the test was run' as opposed to 'I tested X' or 'I ran the test') is one of those things that many of use were taught to do at school, but actually is actively penalised in publishing now. Avoid as much as possible. -->
Statistical analyses were conducted in R version 4.0.3 [@r_core_team_2020]. 

<!-- The more I think about it, the more I think that the stats described below are not really what we're interested in. As we've discussed, of course probability of being NES is dependent on category, because both NES and category are dependent on AOH. All NES are in a threatened RL category. What we're really interested in is whether the extent to which you are 'No Exit' (i.e. how far you are from the threshold) depends on (1) taxonomic class; (2) biogeographic realm; and (3) the absolute value of AOH/AOH threshold. This is essentially the second analysis below, which I now think should be the only one we report on. -->

<!-- In order to compare the effect of class, realm, and habitat category on whether a species is a no exit species, a generalized linear regression (GLM) with binomial distribution was ran on the data set that contained the number of species within each realm.  -->

The degree to which species are constrained from future downlisting by current AOH was captured by the relative distance of AOH from the downlisting threshold. This 'proximity to threshold' measure was calculated as the absolute difference between a species' AOH and the threshold for downlisting to the next lowest Red List category, divided by the maximum possible difference. Thus, proximity to threshold is a standardised measure that accounts for the fact that thresholds between categories do not increase linearly. As an example, a species with 1250 km^2^ AOH has a larger absolute difference to the downlisting threshold (2000 - 1250 = 750 km^2^) than a species with 5 km^2^ AOH (10 - 5 = 5 km^2), but both have a relative proximity to threshold of 0.5. We used a generalized linear model (GLM) with a Poisson distribution, using the function `glm` in the `lme4` R  package [@bates_fitting_2015], to test whether proximity to threshold varied by taxonomic class, biogeography and absolute AOH. Model inference was based on Likelihood Ratio Tests, dropping each variable in tern and comparing the reduced model to the full model [@zuur_mixed_2009].

<!-- To test the significance of class, realm, and category on the difference to next threshold, a linear regression was ran for each of the variables as the dependent variable and Difference / Max Difference as the independent variable. The independent variable divides the difference to next threshold by the max difference possible for each threshold in order to standardize the differences across habitat category.  -->

<!-- Finally, a Chi-squared test was used to test the statistical dependence of class and habitat category.  -->

# Results

# Discussion


## Data availability 

The datasets used to support the findings of this study are available for download by request from their respective providers. Species assessments can be accessed from the IUCN Red List of Threatened Species website at https://www.iucnredlist.org, and range maps can be requested at https://www.iucnredlist.org/resources/spatial-data-download. Protected area maps can be requested from the World Database on Protected Areas, found at https://www.unep-wcmc.org/resources-and-data/analysis/main/wdpa. 

## Code availability

Custom Python code to calculate species Area of Habitat in Google Earth Engine will be published at a later date, and is available on request from R.A.S.

## Acknowledgements

Funding for this research was provided by the High Meadows Environmental Institute and High Meadows Foundation.

## Author contributions

R.A.S. and D.S.W. conceived the study. R.A.S. collated the data. S.R. carried out the analyses and wrote the first draft of the manuscript, with substantial contribution from R.A.S. and D.S.W. 

## Competing interests

The authors declare no competing interests.

# References
