---
title: "Project ideas"
subtitle: "_Estimating the recovery potential of threatened species_"
author: "Rebecca Senior, Sophia Richter"
date: "7 June 2021"
output: 
    bookdown::html_document2:
        toc: true
link-citations: yes
biblio-style: apalike
bibliography: [../writing/refs.bib, ../writing/funky-refs.bib, ../writing/pckgs.bib]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Background

* Habitat loss is far-and-away the biggest driver of biodiversity loss, with no end in sight as the human population continues to grow and develop [@maxwell_biodiversity:_2016; @wwf_living_2020]
* Quantity and quality of remaining habitat is a critical determinant of species' risk of extinction, directly reflected in criterion B ('Geographic range') of the criteria used to list species on the IUCN Red List [@mace_quantification_2008; @iucn_iucn_2020]
  * __Under criterion B, 'Geographic range', a species is listed as Critically Endangered, Endangered or Vulnerable, if, for 5 years or more, they have an Area of Occupancy (AOO) smaller than 10, 500 and 2000 km^2, respectively__
* Appropriately, habitat protection is the most commonly implemented conservation intervention, typically taking the form of Protected Areas that span a range of protection levels
* Protected Areas, when well-managed, do work [@geldmann_effectiveness_2013;geldmann_global-level_2019]
  * Rates of habitat conversion/species loss/population declines lower than they would otherwise be
  * Many co-benefits e.g. carbon storage and sequestration, empowering and protecting indigenous communities, potential to buffer biodiversity from other threats, such as climate change and overexploitation
* PA coverage has increased dramatically in recently years, particularly as a result of the Convention on Biological Diversity (CBD) target to protect 17% of terrestrial surface by 2020 [@hirsch_global_2010]
* New targets of "30x30" i.e. 30% protection by 2030 indicate that PA network will continue to grow
* The question that remains, however, is whether rates of habitat protection are sufficient, relative to rates of habitat loss
* Broadly, we have seen no slowing of biodiversity loss despite the steady increase in conservation effort (including PAs) and funding [@tittensor_mid-term_2014]

# Methods

* Following, Brooks _et al._ 2019 [@brooks_measuring_2019], AOH was determined for all terrestrial birds threatened with habitat loss listed as a major threat on the IUCN Red List [@iucn_iucn_2020], by refining range polygons to areas with suitable land cover and elevation. Range data were downloaded from BirdLife International and the Red List website [@birdlife_2020; @iucn_iucn_2020]. 
* Habitat preference and elevation limits for each species were obtained from the IUCN Red List [@iucn_iucn_2020]
* Land cover from ESA CCI [@esacci_2017], available globally at a 300 m resolution, and annually from 1992-2015
* Habitat preferences matched to land-cover classes using a published crosswalk [@santini_applying_2019]
* For elevation we used the EarthEnv Digital Elevation Model Version 1 [@robinson_earthenv-dem90:_2014]
  * Available at a resolution of 90 m and near-global extent
* The WDPA was cleaned in Google Earth Engine [@hanson_protected-areas_2020], following best practice guidelines [@butchart_shortfalls_2015; @protectedplanet_best-practice_2020]
* AOH was calculated separately for each species in each year, to quantify amount of habitat and its change over time
* For each year, we filtered the WDPA to the PAs established in or prior to that year and then calculated area of overlap between each AOH patch and PAs
* All spatial analyses conducted in Google Earth Engine [@gorelick_google_2017]

# Questions

## Habitat quantity

* How many species have an AOH smaller than the thresholds used by the IUCN to classify species as Vulnerable (10 km^2^), Endangered (500 km^2^) or Critically Endangered (2000 km^2)?
* For those species falling below the threshold, how much below the threshold are they? In other words, how much additional habitat area would it take to move these species up into the next best category? 
* For those species falling below the threshold - what are they? How many birds, mammals and amphibians? What size? Where are they found? Are they habitat specialists?

## Habitat protection

* What is the distribution of protection? How much of a species' AOH typically falls within PAs?
* If species lose all of their AOH that is not protected, do they have enough remaining to stay in their current category or would they qualify for uplisting to a Red List category with a greater risk of extinction? E.g. move from Endangered to Critically Endangered.

## Time series

* How do the above patterns change over time? We have data available from 1992-2015, when many areas would have experienced a change in land cover type and, with that, a change in species' AOH

## Population size

* The questions above could be delved into more thoroughly by considering population sizes that can be supported by each discrete habitat patch within a species total, global habitat
* The data for this is taking a while to gather because it's very computationally intensive, but hopefully I will have it later this month and we can add it in

# References