```{r setup, include=FALSE, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

```{r other-setup, eval = TRUE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(sf)
library(cowplot)
```

# Prep data

```{r data}
realm_ctry_info <- readRDS("/scratch/network/rsenior/conservation-actions/spatial/realm_ctry_info.Rds")

# Main data
trait_df <- 
  read.csv("/scratch/network/rsenior/hmei-internship/crs_top25.csv") %>% 
  mutate(
    # Match species name to how it appears in occurrence dataframe
    scientificName = gsub(" ", "_", scientificName)) %>% 
  filter(!(is.na(CRS)),
         !(is.na(top25))) %>% 
  dplyr::select(scientificName, phylumName, orderName, className, familyName,
                redlistCategory, areaAOH, areaAOHinPA, 
                Category, Difference, CRS, top25)

# Realm spatial data
realm_df <- 
  readRDS("/scratch/network/rsenior/conservation-actions/spatial/realm_df.Rds") %>% 
  filter(!(is.na(realm)))
realm_polys <- read_sf("/scratch/network/rsenior/conservation-actions/spatial/realms_wgs84.shp")

# Country spatial data
country_df <- 
  readRDS("/scratch/network/rsenior/conservation-actions/spatial/country_df.Rds") %>% 
  filter(!(is.na(country)))
country_polys <- read_sf("/scratch/network/rsenior/conservation-actions/spatial/gadm36_0.shp")
```

```{r prep-occdf-fn}
# Function to map species richness
prep_occdf <- function(trait_df, var, occ_df, tax_class, mincells){
  # Subset trait data to the taxonomic class and species with AOH data
  spp_df <- 
    trait_df %>%
    filter(
      # Taxonomic class
      className == tax_class,
      # Species that appear in the occurrence dataframe
      scientificName %in% colnames(occ_df))
  # Coerce variable of interest to numeric (TRUE = 1, FALSE = 0)
  spp_df[,var] <- as.numeric(spp_df[,var]) 
  # Species that have value of 1
  sppTrue <- spp_df[which(spp_df[,var] == 1), "scientificName"]
  # Species that have value of 0
  sppFalse <- spp_df[which(spp_df[,var] == 0), "scientificName"]
  
  # Return NA if there are no species (i.e. all have NA for variable of interest)
  if(length(sppTrue) == 0 & length(sppFalse) == 0) return(NULL)
  
  # Gather into df
  occ_df_sum <- 
    data.frame(
      # Coordinates
      lat = occ_df[,2],
      lon = occ_df[,1],
      # Number of species with TRUE
      n_spT = rowSums(occ_df[, which(colnames(occ_df) %in% sppTrue), drop = FALSE], na.rm = TRUE),
      # Number of species with FALSE
      n_spF = rowSums(occ_df[, which(colnames(occ_df) %in% sppFalse), drop = FALSE], na.rm = TRUE)
      ) %>% 
    mutate(
      # Total species
      spN = n_spT + n_spF,
      # Proportion of species with value of TRUE for variable of interest
      prop = 100 * (n_spT/spN)) %>% 
    # Drop cells with zero species
    filter(spN > 0) %>% 
    mutate(className = tax_class)
  occ_df_sum[,"action"] <- var
  
  # Return
  if(nrow(occ_df_sum) < mincells) {
    return(NULL)
  }else {return(occ_df_sum)}
}

# Function to capitalise first letter of the first word of a string
simpleCap <- function(x) {
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),
      sep="", collapse=" ")
}
```

```{r prep-crs-df}
aoh_dir <- "/scratch/network/rsenior/conservation-actions/aoh/"
crs_df <- 
  lapply(c("amphibia", "aves", "mammalia"), function(tax){
    prep_occdf(trait_df = trait_df,
               var = "CRS",
               occ_df = readRDS(paste(aoh_dir, tax, "_occ.Rds", sep = "")),
               tax_class = tax,
               mincells = 0) %>% 
      mutate(className = simpleCap(tax),
             coords = paste(lon, lat, sep = "_")) %>% 
      filter(n_spT > 0) %>% 
      left_join(select(realm_df, -c(lat, lon)), by = "coords") %>% 
      left_join(select(country_df, -c(lat, lon)), by = "coords")
  })

# Summarise by realm
crs_realm_total <-
  trait_df %>%
  filter(CRS == 1) %>% 
  bind_rows() %>% 
  left_join(readRDS("/scratch/network/rsenior/conservation-actions/spatial/realm_ctry_info.Rds"), 
            by = "scientificName") %>% 
  filter(!(is.na(realms))) %>% 
  # Separate - species occurs in multiple rows if range across multiple realms
  separate_rows(realms, sep = ";") %>% 
  rename(realm = realms) %>% 
  # Count species of each class, in each realm
  group_by(realm, className) %>% 
  summarise(n = n())
# Split into list
crs_realm_total <- split(crs_realm_total, crs_realm_total$className)

# Join to spatial data
crs_realm_total_polys <-
  lapply(crs_realm_total, function(i){
    left_join(realm_polys, i, by = c("Realm" = "realm")) %>%
      filter(!(is.na(className)))
  })

# Repeat for country
crs_country_total <-
  trait_df %>%
  filter(CRS == 1) %>% 
  bind_rows() %>% 
  left_join(readRDS("/scratch/network/rsenior/conservation-actions/spatial/realm_ctry_info.Rds"), 
            by = "scientificName") %>% 
  filter(!(is.na(countries))) %>% 
  # Separate - species occurs in multiple rows if range across multiple countries
  separate_rows(countries, sep = ";") %>% 
  rename(country = countries) %>% 
  # Count species of each class, in each country
  group_by(country, className) %>% 
  summarise(n = n())
# Split into list
crs_country_total <- split(crs_country_total, crs_country_total$className)

# Join to spatial data
crs_country_total_polys <-
  lapply(crs_country_total, function(i){
    left_join(country_polys, i, by = c("NAME_0" = "country")) %>%
      filter(!(is.na(className)))
  })
```

```{r prep-top25-df}
aoh_dir <- "/scratch/network/rsenior/conservation-actions/aoh/"
top25_df <- 
  lapply(c("amphibia", "aves", "mammalia"), function(tax){
    prep_occdf(trait_df = trait_df,
               var = "top25",
               occ_df = readRDS(paste(aoh_dir, tax, "_occ.Rds", sep = "")),
               tax_class = tax,
               mincells = 0) %>% 
      mutate(className = simpleCap(tax),
             coords = paste(lon, lat, sep = "_")) %>% 
      filter(n_spT > 0) %>% 
      left_join(select(realm_df, -c(lat, lon)), by = "coords") %>% 
      left_join(select(country_df, -c(lat, lon)), by = "coords")
  })

# Summarise by realm
top25_realm_total <-
  trait_df %>%
  filter(top25 == 1) %>% 
  bind_rows() %>% 
  left_join(readRDS("/scratch/network/rsenior/conservation-actions/spatial/realm_ctry_info.Rds"), 
            by = "scientificName") %>% 
  filter(!(is.na(realms))) %>% 
  # Separate - species occurs in multiple rows if range across multiple realms
  separate_rows(realms, sep = ";") %>% 
  rename(realm = realms) %>% 
  # Count species of each class, in each realm
  group_by(realm, className) %>% 
  summarise(n = n())
# Split into list
top25_realm_total <- split(top25_realm_total, top25_realm_total$className)

# Join to spatial data
top25_realm_total_polys <-
  lapply(top25_realm_total, function(i){
    left_join(realm_polys, i, by = c("Realm" = "realm")) %>%
      filter(!(is.na(className)))
  })

# Repeat for country
top25_country_total <-
  trait_df %>%
  filter(top25 == 1) %>% 
  bind_rows() %>% 
  left_join(readRDS("/scratch/network/rsenior/conservation-actions/spatial/realm_ctry_info.Rds"), 
            by = "scientificName") %>% 
  filter(!(is.na(countries))) %>% 
  # Separate - species occurs in multiple rows if range across multiple countries
  separate_rows(countries, sep = ";") %>% 
  rename(country = countries) %>% 
  # Count species of each class, in each country
  group_by(country, className) %>% 
  summarise(n = n())
# Split into list
top25_country_total <- split(top25_country_total, top25_country_total$className)

# Join to spatial data
top25_country_total_polys <-
  lapply(top25_country_total, function(i){
    left_join(country_polys, i, by = c("NAME_0" = "country")) %>%
      filter(!(is.na(className)))
  })
```

# Map CRS

```{r map-CRS-raw}
# Make maps!
map_CRS <-
  lapply(crs_df, function(i){
    ggplot() +
      # Plot background realms
      geom_raster(data = realm_df,
                  aes(x = lon, y = lat),
                  fill = "grey") +
      # Plot number of species per grid cell with TRUE (CRS species)
      geom_raster(data = i, 
                  aes(x = lon, y = lat,
                      fill = n_spT)) +
      facet_wrap(~ className, ncol = 1) +
      theme_void() +
      theme(strip.text = element_text(size = 12, hjust = 0, face = "bold"),
            legend.position = "bottom") +
      scale_fill_viridis_c(na.value = "transparent", 
                           name = "No. CRS") +
      guides(fill = guide_colourbar(barwidth = unit(8, "cm"),
                                    barheight = unit(0.3, "cm"),
                                    title.position = "top",
                                    title.hjust = 0.5))
  })
# Combine maps for each class into a single figure with panels
map_CRS_combi <- plot_grid(plotlist = map_CRS, ncol = 1)

# Save
ggsave(plot = map_CRS_combi,
       filename = "/scratch/network/rsenior/hmei-internship/crs_map.png",
       width = 12, height = 20, units = "cm", dpi = 800)
```

```{r map-CRS-realm}
# Define lookup needed to capitalise class names that are used as facet labels
class_lookup <- sapply(names(crs_realm_total_polys), simpleCap)

map_CRS_realm <-
  # Just for amphibians, birds & mammals (indices 1, 2 and 4)
  lapply(crs_realm_total_polys[c(1,2,4)], function(taxon){
    ggplot(taxon) +
      geom_sf(data = realm_polys, 
              colour = "transparent", 
              fill = "grey") +
      geom_sf(data = taxon,
              aes(fill = n),
              colour = "transparent") +
      facet_wrap(~ className, ncol = 1, 
                 labeller = labeller(className = class_lookup)) +
      theme_void() +
      theme(strip.text = element_text(size = 12, hjust = 0, face = "bold"),
            legend.position = "bottom",
            legend.title = element_text(size = 10),
            legend.key.size = unit(0.4, "cm"),
            legend.box = "vertical") +
      scale_fill_gradientn(name = "Total CRS",
                           na.value = "transparent", 
                           colours = RColorBrewer::brewer.pal(9, "YlOrRd")[2:9]) +
      guides(fill = guide_colourbar(barwidth = unit(5, "cm"),
                                    barheight = unit(0.3, "cm"),
                                    title.position = "top",
                                    title.hjust = 0.5))
  })
map_CRS_realm_combi <- cowplot::plot_grid(plotlist = map_CRS_realm, ncol = 1)

ggsave(plot = map_CRS_realm_combi,
       filename = "/scratch/network/rsenior/hmei-internship/crs_map_realm.png",
       width = 12, height = 20, units = "cm", dpi = 800)
```

```{r map-CRS-country}
class_lookup <- sapply(names(crs_country_total_polys), simpleCap)

map_CRS_ctry <-
  lapply(crs_country_total_polys[c(1,2,4)], function(taxon){
    ggplot(taxon) +
      geom_sf(data = realm_polys, 
              colour = "transparent", 
              fill = "grey") +
      geom_sf(data = taxon,
              aes(fill = n),
              colour = "transparent") +
      facet_wrap(~ className, ncol = 1, 
                 labeller = labeller(className = class_lookup)) +
      theme_void() +
      theme(strip.text = element_text(size = 12, hjust = 0, face = "bold"),
            legend.position = "bottom",
            legend.title = element_text(size = 10),
            legend.key.size = unit(0.4, "cm"),
            legend.box = "vertical") +
      scale_fill_gradientn(name = "Total CRS",
                           na.value = "transparent", 
                           colours = RColorBrewer::brewer.pal(9, "YlOrRd")[2:9]) +
      guides(fill = guide_colourbar(barwidth = unit(5, "cm"),
                                    barheight = unit(0.3, "cm"),
                                    title.position = "top",
                                    title.hjust = 0.5))
  })
map_CRS_ctry_combi <- cowplot::plot_grid(plotlist = map_CRS_ctry, ncol = 1)
ggsave(plot = map_CRS_ctry_combi,
       filename = "/scratch/network/rsenior/hmei-internship/crs_map_country.png",
       width = 12, height = 20, units = "cm", dpi = 800)
```

# Map top 25%

```{r map-top25-raw}
# Make maps!
map_top25 <-
  lapply(top25_df, function(i){
    ggplot() +
      # Plot background realms
      geom_raster(data = realm_df,
                  aes(x = lon, y = lat),
                  fill = "grey") +
      # Plot number of species per grid cell with TRUE (top25 species)
      geom_raster(data = i, 
                  aes(x = lon, y = lat,
                      fill = n_spT)) +
      facet_wrap(~ className, ncol = 1) +
      theme_void() +
      theme(strip.text = element_text(size = 12, hjust = 0, face = "bold"),
            legend.position = "bottom") +
      scale_fill_viridis_c(na.value = "transparent", 
                           name = "No. top25") +
      guides(fill = guide_colourbar(barwidth = unit(8, "cm"),
                                    barheight = unit(0.3, "cm"),
                                    title.position = "top",
                                    title.hjust = 0.5))
  })
# Combine maps for each class into a single figure with panels
map_top25_combi <- plot_grid(plotlist = map_top25, ncol = 1)

# Save
ggsave(plot = map_top25_combi,
       filename = "/scratch/network/rsenior/hmei-internship/top25_map.png",
       width = 12, height = 20, units = "cm", dpi = 800)
```

```{r map-top25-realm}
# Define lookup needed to capitalise class names that are used as facet labels
class_lookup <- sapply(names(top25_realm_total_polys), simpleCap)

map_top25_realm <-
  # Just for amphibians, birds & mammals (indices 1, 2 and 4)
  lapply(top25_realm_total_polys[c(1,2,4)], function(taxon){
    ggplot(taxon) +
      geom_sf(data = realm_polys, 
              colour = "transparent", 
              fill = "grey") +
      geom_sf(data = taxon,
              aes(fill = n),
              colour = "transparent") +
      facet_wrap(~ className, ncol = 1, 
                 labeller = labeller(className = class_lookup)) +
      theme_void() +
      theme(strip.text = element_text(size = 12, hjust = 0, face = "bold"),
            legend.position = "bottom",
            legend.title = element_text(size = 10),
            legend.key.size = unit(0.4, "cm"),
            legend.box = "vertical") +
      scale_fill_gradientn(name = "Total top25",
                           na.value = "transparent", 
                           colours = RColorBrewer::brewer.pal(9, "YlOrRd")[2:9]) +
      guides(fill = guide_colourbar(barwidth = unit(5, "cm"),
                                    barheight = unit(0.3, "cm"),
                                    title.position = "top",
                                    title.hjust = 0.5))
  })
map_top25_realm_combi <- cowplot::plot_grid(plotlist = map_top25_realm, ncol = 1)

ggsave(plot = map_top25_realm_combi,
       filename = "/scratch/network/rsenior/hmei-internship/top25_map_realm.png",
       width = 12, height = 20, units = "cm", dpi = 800)
```

```{r map-top25-country}
class_lookup <- sapply(names(top25_country_total_polys), simpleCap)

map_top25_ctry <-
  lapply(top25_country_total_polys[c(1,2,4)], function(taxon){
    ggplot(taxon) +
      geom_sf(data = realm_polys, 
              colour = "transparent", 
              fill = "grey") +
      geom_sf(data = taxon,
              aes(fill = n),
              colour = "transparent") +
      facet_wrap(~ className, ncol = 1, 
                 labeller = labeller(className = class_lookup)) +
      theme_void() +
      theme(strip.text = element_text(size = 12, hjust = 0, face = "bold"),
            legend.position = "bottom",
            legend.title = element_text(size = 10),
            legend.key.size = unit(0.4, "cm"),
            legend.box = "vertical") +
      scale_fill_gradientn(name = "Total top25",
                           na.value = "transparent", 
                           colours = RColorBrewer::brewer.pal(9, "YlOrRd")[2:9]) +
      guides(fill = guide_colourbar(barwidth = unit(5, "cm"),
                                    barheight = unit(0.3, "cm"),
                                    title.position = "top",
                                    title.hjust = 0.5))
  })
map_top25_ctry_combi <- cowplot::plot_grid(plotlist = map_top25_ctry, ncol = 1)
ggsave(plot = map_top25_ctry_combi,
       filename = "/scratch/network/rsenior/hmei-internship/top25_map_country.png",
       width = 12, height = 20, units = "cm", dpi = 800)
```
