---
output:
    bookdown::word_document2:
        reference_docx: coverletter_template.docx
fontsize: 12pt
geometry: margin=2.5cm
mainfont: Calibri
lang: en-GB
papersize: a4
documentclass: article
header-includes:
- \usepackage{hyperref}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \fancyhf{}
- \fancyfoot[CO,CE]{\thepage}
- \usepackage{setspace}
- \doublespacing
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "../")
knitr::opts_chunk$set(echo = FALSE,message = FALSE,error = FALSE, warning = FALSE,
                      dpi = 300, fig.path = "output/", fig.align = "center", 
                      fig.width = 16.6/2.54, fig.height = 15/2.54)
```

Dear Editor,

Please find the attached manuscript "No exit: the conservation reliance of species with little remaining habitat", for consideration as a Practice and Policy article in _Conservation Biology_. 

The ongoing and pervasive threat of habitat conversion has left many species with small and highly fragmented habitats. A suite of factors - from environmental, demographic, and genetic stochasticity to edge effects - renders these species at high risk of extinction, reliant on periodic conservation monitoring and management to safeguard their future in the wild. Here, using newly available tools to quantify habitat area, we find that 2489 (64%) out of 3869 assessed threatened species can never exit threatened status on the IUCN Red List due to habitat constraints. That is, the remaining habitat area for each of these "No Exit Species" is < 2,000 km^2^, the threshold for classifying species as threatened based on area of habitat. No amount of conservation effort can recover No Exit species without accompanying gains in habitat area, likely through restoration.

Habitat restoration is gaining traction in conservation policy and practice, particularly in this UN Decade on Ecosystem Restoration. The magnitude of restoration required, however, is sobering. We determined that, due to limited available habitat, most No Exit Species are closer to the Red List threshold for uplisting (increased extinction risk) than they are to the threshold for downlisting (decreased extinction risk). Thus, gains in habitat must also be matched with robust protection. The majority of No Exit Species are concentrated in a few key countries, including Colombia, Mexico, Madagascar, and Indonesia, all of which (and many more) have committed to protect at least 30% of land and oceans by 2030.

Identifying species that are conservation reliant is essential to directing policy and practice. Given the relevance of our findings to biodiversity conservation, we believe that our study is highly relevant to readers of Conservation Biology, including researchers, conservation practitioners, and advocates.

